Enable the consumer to commit an offset with metadata
zio/zio-kafka pull request #1067
Opened 2023-10-04 09:37 UTC by flavienbert

closed #1066

2023-10-04 11:58 UTC, erikvanoosten commented
@flavienbert I have in my plans to merge commits into a single commit. Is that still possible when there is metadata attached to the commit?

2023-10-04 12:03 UTC, flavienbert commented
@erikvanoosten yes I think. The apache kafka consumer client take an `OffsetAndMetadata` so it should be OK.

2023-10-04 12:16 UTC, erikvanoosten commented
> @erikvanoosten yes I think. The apache kafka consumer client take an `OffsetAndMetadata` so it should be OK.

Ah I see. When we merge commits, per partition we keep the `OffsetAndMetadata` with the highest offset. It means we'll loose the metadata of earlier commits, but that is actually okay; those commits are no longer needed because they have been superseded by a newer one.

2023-10-04 12:37 UTC, flavienbert commented
One point is not cover by this PR: the metadata from the `CommittableRecord.offset` will be always empty: https://github.com/zio/zio-kafka/blob/6e451121b148e4997f1318b5807e83b8d0e6fdf9/zio-kafka/src/main/scala/zio/kafka/consumer/CommittableRecord.scala#L48. This PR only able to publish metadata from consumer stream, not retrieve it when you consume a stream. Is it something you want to add too @erikvanoosten? (if it's yes, is it same PR or an other)

2023-10-04 13:30 UTC, flavienbert commented
As I mentioned in the previous comment, I think is not possible to get metadata from a ZStream with the Consumer because the API `ConsumerRecord` doesn't expose the metadata.

2023-10-04 15:00 UTC, flavienbert commented
Maybe we should put this method private: 
`private[consumer] def metadata: Option[String]` in the Offset trait ? 
To make sure a user didn't try to get the metadata of an offset from the `ConsumerRecord`. Because It will always return None anyway otherwise.

2023-10-04 16:03 UTC, erikvanoosten commented
> Maybe we should put this method private: `private[consumer] def metadata: Option[String]` in the Offset trait ? To make sure a user doesn't try to get the metadata of an offset from the `ConsumerRecord`. Because It will always return None anyway otherwise.

Are you referring to a `CommittableRecord`?

I don't like that because it will mean that you can set the metadata but you can't read it back.

2023-10-04 16:11 UTC, erikvanoosten reviewed
Not done yet, but I wanted to submit these comments already.

2023-10-04 17:21 UTC, erikvanoosten commented
Okay, I am changing my mind 🙂 The `offset` method from `CommitableRecord` should indeed not have a metadata field because that doesn't make sense. Unfortunately, that also means that the `withMetadata` method (the basis of this PR) doesn't make sense. (Off topic, there is more in `Offset` that doesn't make sense. In particular, there shouldn't be a `commit` method in it. @guizmaii is trying to change this part of zio-kafka for a good reason.)

What about adding methods `commitWithMetadata` and `commitOrRetryWithMetadata`?

2023-10-04 18:01 UTC, flavienbert commented
Agree with you `commit` method shouldn't be here. I am not sure `commitWithMetadata` could work because we usually use `commit` after `.aggregateAsync(Consumer.offsetBatches)` this means we call `commit` on the most recent  offset. 

But in my case I need to set the metadata for each offset, and then the most recent offset is commit with the metadata set earlier for sample: 

```
     ...
     offsetOpt  <- offsetState match {
                                 case Committable =>
                                    ZIO.some(record.offset)

                                 case CommittableWithMetadata =>
                                   StorageService
                                       .put(state, record.offset.topic, record.offset.partition)
                                       .map(versionId => Some(record.offset.withMetadata(versionId)))

                                 case NotCommittable => ZIO.none
                               }
        } yield offsetOpt
      }
      .map(_.toSeq)
      .flattenIterables
      .aggregateAsync(Consumer.offsetBatches)
      .mapZIO(_.commit)
``` 

And what about having this model:

```
sealed trait Offset {

  type Self <: Offset

  def topic: String
  def partition: Int
  def offset: Long
  def consumerGroupMetadata: Option[ConsumerGroupMetadata]

  /**
   * Converts this instance of Offset to a CommittableOffset (increment the offset)
   */
  def toCommittableOffset: CommittableOffset

  final lazy val topicPartition: TopicPartition = new TopicPartition(topic, partition)
}

sealed trait CommittableOffset extends Offset {

  type Self <: CommittableOffset

  def commit: Task[Unit]
  def batch: OffsetBatch
  def addMetadata(metadata: String): Self
  def metadata: Option[String]

  private[consumer] def asJavaOffsetAndMetadata: OffsetAndMetadata = new OffsetAndMetadata(offset, metadata.orNull)

  /**
   * Attempts to commit and retries according to the given policy when the commit fails with a
   * RetriableCommitFailedException
   */
  final def commitOrRetry[R](policy: Schedule[R, Throwable, Any]): RIO[R, Unit] =
    Offset.commitOrRetry(commit, policy)
}
```

With this model, we could use `Offset` trait for the offset get from the `CommitableRecord` and then if you want to commit or add metadata you should convert this Offset to a `CommitableOffset` which will be able to commit. And we could introduce an implicit conversion from `Offset` to `CommitableOffset` to avoid breaking changes.

2023-10-04 19:20 UTC, erikvanoosten commented
Okay, I understand your use case,
And I like your thinking. `CommittableOffset` is indeed a reasonable way to model this. This is a breaking change though, even with an implicit conversion it will not be binary compatible (we don't really have that as a goal so it could still be fine).
Since not many people use metadata for commits, IMHO source compatibility is required.

@guizmaii WDYT?

2023-10-05 09:52 UTC, flavienbert commented on zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala
> +                       .runDrain *>
in the function `provideSomeLayer` I need the variable `client` created in the for comprehension. So I can't use `provideSomeLayer` as you mentioned

2023-10-05 10:12 UTC, flavienbert commented
I published a version with `CommittableOffset`. To be honest I like this new version. I think it's much more understandable. There is different models between offsets get from the consumer and offsets that you want to commit.

However, there is one breaking change: you have to explicitly convert `ReadOnlyOffset` to `CommitableOffset`in order to commit offsets: `offset.nextCommittableOffset.commit`. But I prefer explicit conversion this way users can understand how it works internally. 

@erikvanoosten let me know your point of view.

2023-10-05 10:13 UTC, erikvanoosten commented on zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala
> +                       .runDrain *>
Ah yes, I see.

2023-10-10 06:09 UTC, flavienbert commented
@erikvanoosten any updates? Could be great to have the metadata commitment feature merged.

2023-10-10 19:47 UTC, erikvanoosten commented
> @erikvanoosten any updates? Could be great to have the metadata commitment feature merged.

I have asked @svroonland and @guizmaii to also take a look at this PR.

Since we want to change this API in near future, and changing this many times is not nice for our users, for me source compatibility would be essential. Perhaps the other committers see this differently...

2023-10-10 19:49 UTC, erikvanoosten commented
BTW, this is a low risk change. If it doesn't work, we can simply revert and all the data is back! 🙂

2023-10-11 07:15 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/Offset.scala
> +  def nextCommittableOffset: CommittableOffset
I don't like this name "nextCommittableOffset". The "next" feels like we're getting the next element in a list
I'd probably prefer something like `asCommittableOffset` or `toCommittableOffset`

2023-10-11 07:24 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/OffsetBatch.scala
> +      val existing = offsets.getOrElse(tp, new OffsetAndMetadata(-1L))
We probably don't want to instantiate more than one `OffsetAndMetadata(-1L)`

2023-10-11 07:28 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> -    val offsets   = cmd.offsets.map { case (tp, offset) => tp -> new OffsetAndMetadata(offset + 1) }
I'm not convinced movint the `+ 1` logic out of this function makes things clearer. 
Making the `+ 1` has the advantage to be explicit about why we need to do this operation: that's part of the "committing process".

While with the new code, this `+ 1` is lost somewhere else and it's harder to make the link between this "commit algorithm" and this "+ 1" operation. 

Unless you convince me why you prefer your solution, I'd prefer to keep this "+ 1 operaton" here

2023-10-11 07:32 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/producer/TransactionalProducer.scala
> -                }.asJava
Same remark as https://github.com/zio/zio-kafka/pull/1067/files#r1354310142

2023-10-11 07:37 UTC, guizmaii commented on zio-kafka-test/src/test/scala/zio/kafka/consumer/SubscriptionsSpec.scala
> +                _.offset.nextCommittableOffset
I'm not of a fan of this new interface we're offering to our users with this chance.
What's the point of exposing `CommittableRecord::offset` if they need to use `CommittableRecord::offset::nextCommittableOffset`?

If we follow the Law of Demeter or principle of least knowledge (See https://en.wikipedia.org/wiki/Law_of_Demeter) the users shouldn't have to use more than one `.`.
Something like:
```scala
val r: CommittableRecord = ...
r.nextCommittableOffset
```

Why do we need to continue to expose `.offset` if we use your next classes?

2023-10-11 07:39 UTC, guizmaii reviewed
See comments

I think there is still some refinement work needed to make this PR mergeable

2023-10-11 07:41 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/Offset.scala
> +  metadata: Option[String]
Why do we need to create 2 new interfaces and 2 new classes to add this optional field?
Why not just add it to the already existing `Offset` trait? 🤔

2023-10-11 09:45 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +      tp -> new OffsetAndMetadata(offset.offset + 1, offset.metadata)
@guizmaii I have no strong opinion on this yet, I was just exploring possibilities. Sorry for that @flavienbert, this aspect is totally not relevant for this PR. If we want this change (probably not) we can do it in another PR.

2023-10-11 09:52 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/Offset.scala
> +  metadata: Option[String]
@guizmaii something like #1076 is what this PR had at first. @flavienbert then discovered an unfortunate consequence (https://github.com/zio/zio-kafka/pull/1067#issuecomment-1747238802).

Although @flavienbert 's PR fixes that problem now, the price (lower usability and backward incompatibility) is high.

Because of that I also prefer the previous design (like #1076). We can also 'fix' the problem by adding a little warning to the `withMetadata` method.

2023-10-11 10:26 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/Offset.scala
> +  metadata: Option[String]
Quoting @flavienbert in the comment you pointed out:
> a user can believe he can retrieve the metadata offset of the CommittableRecord using _.offset.metadata but in fact it will always return None. We should only able to use _.offset.withMetadata("metadata") from my point of view

In my implementation, the `offset.metadata` is private, only the `.withMetadata` is accessible to the user so I'm not sure to see what's the issue 🤔

2023-10-11 10:44 UTC, flavienbert commented on zio-kafka/src/main/scala/zio/kafka/consumer/Offset.scala
> +  def nextCommittableOffset: CommittableOffset
Yes the next is because of `offset + 1`. I think it's nice to put this logic here.

2023-10-11 10:50 UTC, flavienbert commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> -    val offsets   = cmd.offsets.map { case (tp, offset) => tp -> new OffsetAndMetadata(offset + 1) }
We have same issue today: if someone instantiates an `OffsetImpl` with the `offset + 1` because he wants commit this offset, then on your commit method you do again +1. From my point of view it's obvious that if you instantiate a `CommittableOffsetImpl ` it is the offset you want to commit (meaning with offset +1 inside already compute). Then the function commit should only commit this offset. It looks obvious for me but maybe I am wrong

2023-10-11 10:54 UTC, flavienbert commented on zio-kafka-test/src/test/scala/zio/kafka/consumer/SubscriptionsSpec.scala
> +                _.offset.nextCommittableOffset
Because a user should be able to get the current offset of the record. If you don't like the new interface, I get it. Check my first commit. It's much more easier and let me know if you prefer it.

2023-10-11 10:56 UTC, flavienbert commented on zio-kafka/src/main/scala/zio/kafka/consumer/Offset.scala
> +  metadata: Option[String]
Probably first commit is enough!

2023-10-11 10:57 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> -    val offsets   = cmd.offsets.map { case (tp, offset) => tp -> new OffsetAndMetadata(offset + 1) }
There is indeed a disconnect with how zio-kafka tracks offsets (last consumed offset) and what kafka expects (offset to consume). However, the core of this PR is to add metadata to the commits. Lets move the offset discussion to another PR, or maybe to Discord.

2023-10-11 10:59 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/Offset.scala
> +  metadata: Option[String]
Would you mind rolling the branch back to that commit?

2023-10-11 11:00 UTC, flavienbert commented on zio-kafka/src/main/scala/zio/kafka/consumer/Offset.scala
> +  metadata: Option[String]
Ok should I push force the first commit? (with the first reviews fixed)?

2023-10-11 11:18 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/Offset.scala
> +  metadata: Option[String]
Since all PR commits are eventually squashed anyway, you can do whatever works for you: force push the first commit, or add a new commit that reverts to that state...

2023-10-11 11:18 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/Offset.scala
> +  metadata: Option[String]
BTW, if you take the force push route, then fon't forget to rebase on master again.

2023-10-11 12:48 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/Offset.scala
> +  metadata: Option[String]
Needs to be `private[consumer]`

2023-10-11 12:49 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/Offset.scala
> +  metadata: Option[String]
```suggestion
  private[consumer] metadata: Option[String]
```

2023-10-11 13:22 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/Offset.scala
> +  metadata: Option[String]
This is done.

2023-10-11 13:25 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/producer/TransactionalProducer.scala
> +                  topicPartition -> new OffsetAndMetadata(offset.offset + 1, offset.metadata)
We should retain leader epoch here as well.

2023-10-11 14:01 UTC, flavienbert commented on zio-kafka/src/main/scala/zio/kafka/consumer/Offset.scala
> +  metadata: Option[String]
should I remove private ?

2023-10-12 06:26 UTC, erikvanoosten commented
@flavienbert master changed quite a bit, would you like me to rebase it for you?

2023-10-12 06:48 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/Offset.scala
> +  metadata: Option[String]
you need to add `private[consumer]`, same in the interface

2023-10-12 08:06 UTC, flavienbert commented on zio-kafka/src/main/scala/zio/kafka/consumer/Offset.scala
> +  metadata: Option[String]
The OffsetImpl class is already private.

2023-10-12 08:11 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/Offset.scala
> +  metadata: Option[String]
I think it'd be better to give a default value to `metadata: Option[String]`:
```scala
metadata: Option[String] = None
```

2023-10-12 11:03 UTC, flavienbert commented
I rebased my branch, But the CI fail for `sbt ciGenerateGithubWorkflow` but it seems to be good

2023-10-12 12:08 UTC, guizmaii commented on .github/workflows/ci.yml
> -    - gh-pages
You shouldn't have this change

2023-10-12 12:09 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/OffsetBatch.scala
> +      val existing = offsets.getOrElse(tp, new OffsetAndMetadata(-1L))
@flavienbert

2023-10-12 17:18 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/producer/TransactionalProducer.scala
> +                  topicPartition -> new OffsetAndMetadata(offset.offset + 1, offset.metadata)
Never mind. I'll add it later.

2023-10-12 18:32 UTC, erikvanoosten requested changes
Some small suggestions. Otherwise LGTM.

2023-10-12 18:32 UTC, erikvanoosten commented on zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala
> +                       .provideSomeLayer[Kafka](consumer(client, Some(group)))
```suggestion
          // Consume messages
          subscription = Subscription.topics(topic)
          c            = consumer(client, Some(group))
          _ <- Consumer
                 .partitionedStream(subscription, Serde.string, Serde.string)
                 .flatMap(_._2.map(_.offset.withMetadata(metadata)))
                 .take(1)
                 .transduce(Consumer.offsetBatches)
                 .take(1)
                 .mapZIO(_.commit)
                 .runDrain
                 .provideSomeLayer[Kafka](c)
          // Fetch the committed offset
          offsets <- Consumer
                       .committed(Set(new TopicPartition(topic, 0)))
                       .provideSomeLayer[Kafka](c)
```

2023-10-12 18:32 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +            .getOrElse(offset))
```suggestion
          acc.updateWith(tp) { current =>
            current.map(current => if (current.offset() > offset.offset()) current else offset).orElse(Some(offset))
          }
```

2023-10-13 06:21 UTC, erikvanoosten commented on zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala
> +                       .provideSomeLayer[Kafka](consumer(client, Some(group)))
Never mind, not important.

2023-10-13 06:21 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +            .getOrElse(offset))
Never mind, not important.

2023-10-13 06:31 UTC, erikvanoosten approved these changes

2023-10-13 06:50 UTC, guizmaii requested changes
This one still need to be changed: https://github.com/zio/zio-kafka/pull/1067/files#r1354306081

2023-10-13 06:55 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/OffsetBatch.scala
> +      val existing = offsets.getOrElse(tp, new OffsetAndMetadata(-1L))
I am not sure this is important. Using a constant means less memory locality (making the L2 useless).
Instead I would propose this logic is rewritten such that creating a dummy OffsetAndMetadata is not even necessary.

2023-10-15 07:13 UTC, svroonland commented on zio-kafka/src/main/scala/zio/kafka/consumer/Offset.scala
> +  def withMetadata(metadata: String): Offset
We can copy some documentation from here: https://kafka.apache.org/31/javadoc/org/apache/kafka/clients/consumer/OffsetAndMetadata.html

> The Kafka offset commit API allows users to provide additional metadata (in the form of a string) when an offset is committed. This can be useful (for example) to store information about which node made the commit, what time the commit was made, etc.

2023-10-26 17:15 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/OffsetBatch.scala
>          newOffsets += tp -> offset
This is the last thing that is holding the PR from merging. Let's address @guizmaii request by removing the need for the artificial offset completely. @flavienbert WDYT?

```suggestion
      val laterOffset = offsets.get(tp) match {
        case Some(existing) => if (existing.offset < offset.offset) offset else existing
        case None => offset
      }
      newOffsets += tp -> laterOffset
```

2023-10-27 09:03 UTC, guizmaii approved these changes

2023-10-27 09:04 UTC, guizmaii commented
@erikvanoosten You merge once the CI pass :)

2023-10-27 09:04 UTC, guizmaii commented
@flavienbert Thanks for your work :)

2023-10-27 10:23 UTC, erikvanoosten commented
@flavienbert Could you run `sbt fmt` please?

2023-10-27 14:31 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/OffsetBatch.scala
> +        case None => offset
To make the linter happy (sigh):

```suggestion
        case None           => offset
```

2023-10-27 14:32 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/OffsetBatch.scala
> +        case None => offset
@flavienbert I tried to push this change but I do not have access to your fork.

2023-10-27 19:18 UTC, merged

2023-10-28 08:47 UTC, erikvanoosten commented
Thanks for you patience @flavienbert ! This PR is now available in https://github.com/zio/zio-kafka/releases/tag/v2.6.0 🥳