Automatically merge commits
zio/zio-kafka pull request #1073
Opened 2023-10-08 10:39 UTC by erikvanoosten

The commit throughput that is supported by Kafka brokers is much lower than the consume throughput. Therefore, to retain a high consume throughput it is important that not every record's offset is committed. In this PR we automatically merge all commits that were generated in the course of a single run of the runloop. This frees users from having to merge streams and do the commit merging themselves.

Commits are placed in a separate queue. Although this is not really needed for this change, we do need this in the next PR, where we start handling commits from the rebalance listener (see #830).

2023-10-08 20:44 UTC, svroonland requested changes
Nice change, I agree this will be of benefit to users. Could you reduce the PR diff size though? Since the Runloop's behavior is complex and changes can have subtle unintended effects, small diffs really help to review this well. There's some changed comments, part of the commit code is moved to another place and the commit queue, like you mention, is not necessary for this change.

2023-10-09 08:59 UTC, erikvanoosten commented
> Could you reduce the PR diff size though?

Sure, I can split it further.

2023-10-11 08:16 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +  // TODO: make `private` as soon as `State` has been moved into `Runloop`, see https://github.com/zio/zio-kafka/pull/1065
Can be made private now I think 🙂

2023-10-11 08:17 UTC, guizmaii commented
@erikvanoosten Can you make the changes @svroonland asked for, please? So we can more easily review your work 🙂

2023-10-11 09:42 UTC, erikvanoosten commented
> @erikvanoosten Can you make the changes @svroonland asked for, please? So we can more easily review your work 🙂

Yes, I am working on it!

2023-10-11 11:02 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +  // TODO: make `private` as soon as `State` has been moved into `Runloop`, see https://github.com/zio/zio-kafka/pull/1065
This class is gone now.

2023-10-11 17:06 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +    val offsets = commits
`OffsetBatch` is not a straight fit. If `commit` would not be in there, it would be worthwhile to make it work. But I don't see it now. IMHO we can/need to revisit this code together with introducing a more functional commit flow.

Also, IMHO, for now this good enough.

2023-10-11 17:26 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> -      case cmd: RunloopCommand.Commit  => doCommit(cmd).as(state.addCommit(cmd))
We need to handle commits before the other commands. The other commands might stop the subscription, or stuff like that. We have an open issue (#852) about not handling all the commits when the streams are closed. By handling commits first, this is somewhat prevented (we still need a more fundamental solution though).

Because we need the commit command first, we need to `collect` them.

(Aside: in the past we didn't use `collect` for commands, instead we pattern matched inside the `handleCommand` method. You can ask @guizmaii about this change.)

IMHO splitting commit handling over multiple methods will decrease legibility, and is already pretty complex.

Finally, please keep in mind that in the next PR the commits will come from a separate queue and the `collect` is replaced by pulling from the queue.

2023-10-11 17:35 UTC, svroonland approved these changes
Alright

2023-10-11 17:39 UTC, merged

2023-10-12 07:08 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +        .as(newState)
I'd wrap this in a `ZIO.suspendSucced`:
```scala
ZIO.suspendSucced {
      val (offsets, callback, onFailure) = asyncCommitParameters(commits)
      val newState                       = state.addCommits(commits)
      consumer.runloopAccess { c =>
        // We don't wait for the completion of the commit here, because it
        // will only complete once we poll again.
        ZIO.attempt(c.commitAsync(offsets, callback))
      }
        .catchAll(onFailure)
        .as(newState)
}
```

So that all the code is evaluated when the returned `IO` is evaluated. It makes code simpler to follow IMO

2023-10-12 07:13 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +      .toMap
I'd not transform it to an immutable Map here if we transform it to a Java Map later. Feels like an unnecessary extra step

2023-10-12 07:20 UTC, guizmaii commented
Super smart change! Thanks for this Erik 🙂

2023-10-12 07:36 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +        .as(newState)
Good idea. I'll prepare another PR with that change.

2023-10-12 07:38 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +      .toMap
Sure, we can do that as well. Its often a balance between readability and performance. In this going for a java map directly would be about as readable :)

2023-10-12 17:21 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +        .as(newState)
Hmmm, this is a pure method, it doesn't return a ZIO so this suggestion doesn't make sense.

2023-10-12 17:43 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +      .toMap
@guizmaii Exploring the idea here: https://github.com/zio/zio-kafka/pull/1079