Document Serdes in more depth
zio/zio-kafka pull request #1337
Opened 2024-09-29 09:57 UTC by erikvanoosten

Fixes #1331.

2024-09-29 09:58 UTC, erikvanoosten commented
@ytalashko, would you like to review this as well?

2024-09-29 12:15 UTC, svroonland requested changes

2024-09-29 12:15 UTC, svroonland commented on docs/serialization-and-deserialization.md
> +Zio-kafka supports serializers and deserializers (serde) to convert record keys and values to and from byte arrays.
from byte arrays to scala case classes and vice versa.

2024-09-29 12:15 UTC, svroonland commented on docs/serialization-and-deserialization.md
> +val stream = Consumer
This feels quite low level, I don't think we should be promoting byteArray based serdes as the first example here. For most use cases providing the key and value Serde to the `Consumer` is fine, especially if you use `asOption` or `asTry` to handle any errors. If you want to squeeze extra performance, use byteArrays and do your own deserialization.

2024-09-29 18:31 UTC, erikvanoosten commented on docs/serialization-and-deserialization.md
> +val stream = Consumer
For me it is not about performance but more about freedom in how to handle chunks and failure scenarios. Regardless, I don't mind switching the order.

2024-10-02 09:20 UTC, ytalashko approved these changes
> @ytalashko, would you like to review this as well?

Sure

Looks great overall!
Left few minor/optional suggestions

2024-10-02 09:20 UTC, ytalashko commented on docs/serialization-and-deserialization.md
> +val stream = Consumer
I would also vote to have a custom key & value serdes in the first example, since it covers a bit more, e.g. how to send/get desired ADTs to/from kafka, instead of byte arrays, which should easier to start from for some real or showcase application (to me).

2024-10-02 09:20 UTC, ytalashko commented on docs/serialization-and-deserialization.md
> +Below is an example that skips messages that fail to deserialize. The offset is passed downstream to be committed.
Minor one. I kinda like previous wording more, but maybe it only me.

2024-10-02 09:20 UTC, ytalashko commented on docs/serialization-and-deserialization.md
> +## A warning about `mapZIO`
Great hints/insights inside this section, 👍

2024-10-03 09:47 UTC, erikvanoosten commented on docs/serialization-and-deserialization.md
> +Zio-kafka supports serializers and deserializers (serde) to convert record keys and values to and from byte arrays.
Indeed, this text is not very clear. I improved it in https://github.com/zio/zio-kafka/pull/1337/commits/d5bd32f956a309e7d021a569d45328395eba2252

2024-10-03 09:48 UTC, erikvanoosten commented on docs/serialization-and-deserialization.md
> +val stream = Consumer
Alright. In https://github.com/zio/zio-kafka/pull/1337/commits/d5bd32f956a309e7d021a569d45328395eba2252 we no longer recommend handling data in the consumer stream as the primary solution, and using `.asTry` is the first offered solution.

2024-10-03 09:48 UTC, erikvanoosten commented on docs/serialization-and-deserialization.md
> +Zio-kafka supports serializers and deserializers (serde) to convert record keys and values to and from byte arrays.
In https://github.com/zio/zio-kafka/pull/1337/commits/d5bd32f956a309e7d021a569d45328395eba2252 I completely rewrote this paragraph as it was far from clear. Thanks for the comments.

2024-10-03 09:49 UTC, erikvanoosten commented on docs/serialization-and-deserialization.md
> +- How to write a custom serde
Accepted in https://github.com/zio/zio-kafka/pull/1337/commits/d5bd32f956a309e7d021a569d45328395eba2252

2024-10-03 09:49 UTC, erikvanoosten commented on docs/serialization-and-deserialization.md
> +- How to write and use a custom serde that wraps invalid data
Accepted in https://github.com/zio/zio-kafka/pull/1337/commits/d5bd32f956a309e7d021a569d45328395eba2252

2024-10-03 09:49 UTC, erikvanoosten commented on docs/serialization-and-deserialization.md
> +Below is an example that skips messages that fail to deserialize. The offset is passed downstream to be committed.
I am fine with either. Reverted to previous words in https://github.com/zio/zio-kafka/pull/1337/commits/d5bd32f956a309e7d021a569d45328395eba2252.

2024-10-03 09:51 UTC, erikvanoosten commented
@svroonland @ytalashko Thanks for your comments. They were very useful. I have addressed them in https://github.com/zio/zio-kafka/pull/1337/commits/d5bd32f956a309e7d021a569d45328395eba2252.

2024-10-08 12:34 UTC, svroonland reviewed
It would be good to have an example here of deserializing json, with zio-json

2024-10-08 12:43 UTC, svroonland approved these changes

2024-10-08 17:31 UTC, merged