Implements delete records
zio/zio-kafka pull request #411
Opened 2022-01-13 20:03 UTC by mdulac

This is a passthrough function to the Admin Client for deleting records

2022-01-13 20:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zio/zio-kafka?pullRequest=411) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zio/zio-kafka?pullRequest=411) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zio/zio-kafka?pullRequest=411) it.</sub>

2022-01-14 08:00 UTC, strokyl commented
:+1:

2022-01-23 18:30 UTC, svroonland requested changes
Thanks for the contribution! One request regarding the options parameter

2022-01-23 18:30 UTC, svroonland commented on src/main/scala/zio/kafka/admin/AdminClient.scala
> +    deleteRecordsOptions: Option[DeleteRecordsOptions] = None
Most of the admin methods have a scala variant of such an options object, like `listConsumerGroups` has `ListConsumerGroupsOptions`. Can we implement that here as well?

2022-01-24 18:55 UTC, svroonland approved these changes
Looks good, thanks!

2022-01-24 18:55 UTC, svroonland commented on src/main/scala/zio/kafka/admin/AdminClient.scala
> +  case class DeleteRecordsOptions(timeout: Option[Duration]) {
It's a bit weird to have an `Option[DeleteRecordOptions]` which only has an `Option[Duration]` field, but I guess this matches the java API more closely 👍

2022-01-24 18:55 UTC, merged

2022-01-24 18:57 UTC, svroonland commented
I see that there's other methods where we're using the java classes directly, raised an issue for that: https://github.com/zio/zio-kafka/issues/418