Update CI pipelines
zio/zio-kafka pull request #424
Opened 2022-02-01 03:34 UTC by guizmaii

2022-02-01 03:35 UTC, guizmaii commented on .github/workflows/ci.yml
> -        uses: olafurpg/setup-scala@v13
`olafurpg/setup-scala` is deprecated and `sbt` is now installed by default in all the OS proposed by Github Actions

2022-02-01 03:36 UTC, guizmaii commented on .github/workflows/ci.yml
> -        java: ['adopt@1.8', 'adopt@1.11']
AdoptOpenJDK is deprecated and replaced by Eclipse Temurin

2022-02-02 08:44 UTC, svroonland requested changes

2022-02-02 08:44 UTC, svroonland commented on .github/workflows/ci.yml
> +      - uses: coursier/cache-action@v6
Can we keep the action names?

2022-02-02 09:13 UTC, guizmaii commented on .github/workflows/auto-approve.yml
> +    runs-on: ubuntu-latest
Up to you. IMO, we're on the JVM, that doesn't matter much.

2022-02-02 09:21 UTC, guizmaii commented on .github/workflows/auto-approve.yml
> +    runs-on: ubuntu-latest
Done!

2022-02-02 09:21 UTC, guizmaii commented on .github/workflows/ci.yml
> +      - uses: coursier/cache-action@v6
Done!

2022-02-03 08:10 UTC, svroonland approved these changes

2022-02-03 11:20 UTC, merged