Avoid using a `Task` when code is pure. Prefer to use `Try`.
zio/zio-kafka pull request #539
Opened 2022-11-16 19:38 UTC by guizmaii

2023-01-29 10:19 UTC, svroonland requested changes
Looks fine overall, but a few points

2023-01-29 10:19 UTC, svroonland commented on zio-kafka/src/main/scala/zio/kafka/admin/AdminClient.scala
> +    def forEach[B](f: A => Try[B]): Try[List[B]] = {
It's more scala/cats idomatic to have a `List[Try[A]]` and a `sequence: Try[List[A]]` method. Have a look at `Future.sequence` for example.

2023-01-29 10:19 UTC, svroonland commented on zio-kafka/src/main/scala/zio/kafka/admin/AdminClient.scala
> +  implicit final class MapOps[K1, V1](private val v: Map[K1, V1]) extends AnyVal {
IMO the `private` has no added value for these implicit classes, whose only purpose is to define extension methods.

2023-01-30 01:38 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/admin/AdminClient.scala
> +    def forEach[B](f: A => Try[B]): Try[List[B]] = {
`forEach` comes from zio-prelude ;)

2023-01-30 01:39 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/admin/AdminClient.scala
> +  implicit final class MapOps[K1, V1](private val v: Map[K1, V1]) extends AnyVal {
This is just copying how cats and co. are defining implicit class. I know they did a lot of research to find the best way to define them to be sure there is not overhead at runtime, I'm just copying their way of coding here

2023-01-30 07:55 UTC, svroonland commented on zio-kafka/src/main/scala/zio/kafka/admin/AdminClient.scala
> +  implicit final class MapOps[K1, V1](private val v: Map[K1, V1]) extends AnyVal {
Ah I was not aware of that. Alright

2023-01-30 12:13 UTC, svroonland approved these changes

2023-01-30 12:13 UTC, svroonland commented on zio-kafka/src/main/scala/zio/kafka/admin/AdminClient.scala
> +    def forEach[B](f: A => Try[B]): Try[List[B]] = {
Right, makes sense.

2023-02-14 16:52 UTC, jdegoes approved these changes

2023-02-14 16:52 UTC, merged