added missing type annotations
zio/zio-kafka pull request #636
Opened 2023-02-10 13:09 UTC by aashish2054

Added missing type annotation to make code more readable and easy to understand.

2023-02-11 17:54 UTC, svroonland requested changes
Thanks, a few minor comments

2023-02-11 17:54 UTC, svroonland commented on zio-kafka-test/src/test/scala/zio/kafka/ProducerSpec.scala
> +  ): ZIO[Any with Scope, Throwable, Dequeue[Take[Throwable, CommittableRecord[String, RuntimeFlags]]]] =
This should be `CommittableRecord[String, Int]`.

2023-02-11 17:54 UTC, svroonland commented on zio-kafka/src/main/scala/zio/kafka/consumer/ConsumerSettings.scala
> +  private[this] def autoOffsetResetConfig: Map[_ <: String, String] = offsetRetrieval match {
Let's make this `Map[String, String]`

2023-02-11 18:36 UTC, aashish2054 commented
all checks passed, can this be merged?

2023-02-12 16:24 UTC, aashish2054 commented on zio-kafka/src/main/scala/zio/kafka/consumer/ConsumerSettings.scala
> +  private[this] def autoOffsetResetConfig: Map[_ <: String, String] = offsetRetrieval match {
done

2023-02-12 16:24 UTC, aashish2054 commented on zio-kafka-test/src/test/scala/zio/kafka/ProducerSpec.scala
> +  ): ZIO[Any with Scope, Throwable, Dequeue[Take[Throwable, CommittableRecord[String, RuntimeFlags]]]] =
done

2023-02-14 07:42 UTC, svroonland approved these changes

2023-02-14 07:42 UTC, merged