Booting a Consumer without consuming shouldn't throw a `RunloopTimeout` exception
zio/zio-kafka pull request #857
Opened 2023-05-23 10:12 UTC by guizmaii

2023-05-24 10:14 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/Consumer.scala
> -                                .toHub(hubCapacity)
I managed to remove the need for this `Hub` by moving this `ZStream.fromQueue(runloop.partitions)...` creation in the `Consumer::partitionedAssignmentStream` method

2023-05-24 11:40 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/RunloopAccess.scala
> + *   1. The [[Runloop]] has a timeout throwing a [[zio.kafka.consumer.Consumer.RunloopTimeout]] when reached. If the
Why 1. and then 1. again?
Because of: https://contributors.scala-lang.org/t/do-numbered-lists-actually-work-in-scaladoc-markup/2748/2?u=guizmaii

2023-05-25 13:57 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/RunloopAccess.scala
> + * // TODO Jules: DOC TO UPDATE
TODO @guizmaii

2023-05-31 15:07 UTC, erikvanoosten commented
@guizmaii This is quite a sizeable refactoring. Could you guide us through the main ideas? Without those ideas it is hard to see if the implementation is correct. Some questions that pop are:

- Now that the run-loop time out is gone, when a consumer gets stuck processing, will we still stop polling from the broker?
- What is the purpose of using a Hub instead of what we had?
- There is a RunloopState.NotStarted and a RunloopState.Stopped, shall we merge them into a single state?

But please focus on the main ideas first.

2023-06-01 15:03 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/RunloopAccess.scala
> +   * No need to call `Runloop::stopConsumption` if the Runloop has been stopped.
```suggestion
   * No need to call `Runloop::stopConsumption` if the Runloop has not been started or has been stopped.
```

2023-06-04 11:04 UTC, svroonland requested changes
To be quite honest, the PR contains a lot of seemingly unnecessary (for the scope of this PR)  refactorings, rewordings of loggings and moving of code etc that make it hard to review for such a critical piece of functionality. Could you implement this functionality in-place as much as possible first and then have separate refactoring PRs?

2023-06-04 11:36 UTC, guizmaii commented
@svroonland Done. Here's the PR where I do backported the piece of code which I was only refactoring: https://github.com/zio/zio-kafka/pull/901

I also rebase this branch on top of #901 so that this PR diff now only contains the code which is fixing #856

2023-06-05 18:01 UTC, erikvanoosten commented
For now we need to keep the runloop timeout. We can remove it once #902 has been implemented.

2023-06-05 18:34 UTC, erikvanoosten reviewed
Luckily, I am finally seeing the value of this PR. Thanks for that. There is a suggestion below here, I really think we can simplify RunloopAccess a lot. I will review further another time because my head needs a rest from this one 😉

2023-06-05 18:34 UTC, erikvanoosten commented on zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala
> +          } @@ nonFlaky(5),
Is this a flaky test? If so, why?

2023-06-07 12:15 UTC, guizmaii commented on zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala
> +          } @@ nonFlaky(5),
It's testing something non-dertermistic. So we want to be sure that we didn't just get lucky

2023-06-07 13:19 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/RunloopAccess.scala
> +   *      fiber and immediately after forking, stops it. The Runloop will potentially not be started yet.
FYI @erikvanoosten I gave a try to your suggested solution here: https://github.com/zio/zio-kafka/pull/910

It seems to be working fine. The only issue I have is the `.ignore` I have to add here: https://github.com/zio/zio-kafka/pull/910/files#diff-689216f569dbe08f28a5245c0b6d35721937d800ccd3743164e2c42a4ffdb4c6R67
Either we keep this ignore or we change the `stopConsumption` return type to `Task[Unit]`.

WDYT?

2023-06-08 12:53 UTC, svroonland commented
Ah I was hoping the PR would become significantly smaller, but it hasn't 😅  I haven't had time to review it and given the size I can't really do it in between..

2023-06-14 11:49 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +          _ <- partitionsHub.publish(Take.end)
Does it finalize all the Hub's subscriptions?

2023-06-15 14:27 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +          _ <- partitionsHub.publish(Take.end)
No, it doesn't.

2023-06-17 10:07 UTC, erikvanoosten commented on zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala
> +              settings <- consumerSettings(clientId = clientId)
```suggestion
              settings <- consumerSettings(clientId = clientId, runloopTimeout = 1.milli)
```

2023-06-17 10:13 UTC, erikvanoosten commented on zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala
> +            } yield testResult && assert(finalizationEvents)(
Just FYI, ZIO test now also supports `assert(a == b)` instead of `assert(a)(equalTo(b))`.

2023-06-17 10:16 UTC, erikvanoosten commented on zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala
> +                                .plainStream(Subscription.manual(topic -> 0), Serde.string, Serde.string)
This only works if we know that the topic has 1 partition. Otherwise the data might land in another partition. Shall we create the topic explicitly, just to make sure it has only 1 partition?

2023-06-17 10:22 UTC, erikvanoosten commented on zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala
> +          } @@ nonFlaky(5),
With this producer (you could remove the partition stuff):
```scala
  private def scheduledProducer[R](
    topic: String,
    partitionCount: Int,
    schedule: Schedule[R, Any, Long]
  ): ZStream[R with Producer, Throwable, Chunk[RecordMetadata]] =
    ZStream
      .fromSchedule(schedule)
      .mapZIO { i =>
        produceMany(topic, partition = i.toInt % partitionCount, kvs = List(s"key$i" -> s"msg$i"))
      }
```
The producer is slower and runs on its own fiber. With the correct schedule this makes it fairly impossible for the consumer to consumer everything. The test should not be flaky anymore after that. Bonus: we can abort the fiber once the consumer is done making the test a lot faster.

2023-06-17 10:36 UTC, guizmaii commented on zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala
> +                                .plainStream(Subscription.manual(topic -> 0), Serde.string, Serde.string)
I'm sorry, I'm not sure to understand your comment. This test is testing the finalizers order. Not sure to see the relationship between your comment and the test purpose

2023-06-17 10:37 UTC, erikvanoosten commented on zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala
> +                                .plainStream(Subscription.manual(topic -> 0), Serde.string, Serde.string)
It only consumes from partition 0 `Subscription.manual(topic -> 0)`. If the data lands in topic 1, this consumer will see nothing.

2023-06-17 10:41 UTC, guizmaii commented on zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala
> +                                .plainStream(Subscription.manual(topic -> 0), Serde.string, Serde.string)
Oh ok. Well, it never happened neither in CI or locally 🤔

2023-06-17 10:45 UTC, guizmaii commented on zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala
> +          } @@ nonFlaky(5),
> With the correct schedule this makes it fairly impossible for the consumer to consumer everything.

The thing is that this part of the test: `assert(consumed_0)(isLessThan(numberOfMessages.toLong))` is very important. It proves that the consumption has indeed been stopped and so didn't consume everything. 
With your proposal I'm not sure to see how to prove that the consumer didn't consume everything

2023-06-17 11:12 UTC, erikvanoosten commented on zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala
> +          } @@ nonFlaky(5),
My proposal only change the producer, the rest, including that assertion, stays the same.

2023-06-17 11:59 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +              SubscriptionState.Subscribed(subscriptions = Set(newSubscription), union = newSubscription)
A lot of this union code could be cleaned up by moving it into another class. Let's leave that for another PR though.

2023-06-17 13:33 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +              case None => ZIO.fail(InvalidSubscriptionUnion(subs))
There is a problem with throwing an exception here.
Before, this failure would be returned at the place where the stream was created. Now, the failure will stop the runloop.

2023-06-17 13:38 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +  private final val commandQueueSize: Int = 1024
The [naming conventions in the scala style guide](https://docs.scala-lang.org/style/naming-conventions.html#constants-values-and-variables) dictate that this should be written as:
```suggestion
  private final val CommandQueueSize: Int = 1024
```

2023-06-17 13:43 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +  private final val commandQueueSize: Int = 1024
Not necessarily part of this PR...

2023-06-17 13:45 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +  ): URIO[Scope, Runloop] =
I strongly prefer writing out the type fully. I can never remember the mnemonic aliases with R and U. Only `Task` sticks, the rest is overhead.

2023-06-17 14:24 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +              case None => ZIO.fail(InvalidSubscriptionUnion(subs))
Great catch! That's a shame that no tests were written to validate this behaviour. I'll write one and fix this issue.

2023-06-17 14:59 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +              case None => ZIO.fail(InvalidSubscriptionUnion(subs))
Pending this comment, the PR LGTM.
I will play a bit more with making RunloopAccessStates use a Promise. But that does not stop this PR.

2023-06-17 17:34 UTC, erikvanoosten commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +              case None => ZIO.fail(InvalidSubscriptionUnion(subs))
Looks good.

2023-06-18 08:36 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala
> +  ): URIO[Scope, Runloop] =
I'd prefer it to stay like this. If you never use these type aliases you'll never get used to them. IMO, once you're familiar with them they allow us to read code faster

2023-06-18 08:49 UTC, svroonland commented on zio-kafka-bench/src/main/scala/zio/kafka/bench/comparison/ComparisonBenchmark.scala
> +        // Absurdly high timeout to avoid the runloop from being interrupted while we're benchmarking other stuff
Isn't this made obsolete by this PR?

2023-06-18 08:49 UTC, svroonland commented on zio-kafka/src/main/scala/zio/kafka/consumer/Consumer.scala
> -      def extendSubscriptions = subscriptions.updateZIO { existingSubscriptions =>
As I still find this PR quite hard to review, was it functionally necessary to move this code to the Runloop and introduce the SubscriptionState? Not that I'm against that change, but it makes this PR very large and hard to see what the actual behavioral changes are..

2023-06-18 09:15 UTC, guizmaii commented on zio-kafka-bench/src/main/scala/zio/kafka/bench/comparison/ComparisonBenchmark.scala
> +        // Absurdly high timeout to avoid the runloop from being interrupted while we're benchmarking other stuff
Just to be sure, what are you talking about? About the `RunloopTimeout`?

2023-06-18 09:18 UTC, svroonland commented on zio-kafka-bench/src/main/scala/zio/kafka/bench/comparison/ComparisonBenchmark.scala
> +        // Absurdly high timeout to avoid the runloop from being interrupted while we're benchmarking other stuff
I mean, can we remove this setting override from the benchmark? I'd expect it to not cause any errors anymore because the timeout only starts when we start consuming, right?

2023-06-18 09:19 UTC, guizmaii commented on zio-kafka/src/main/scala/zio/kafka/consumer/Consumer.scala
> -      def extendSubscriptions = subscriptions.updateZIO { existingSubscriptions =>
> was it functionally necessary to move this code to the Runloop
I'm explaining this point here: https://github.com/zio/zio-kafka/pull/857#issuecomment-1572256942

If you look attentively at the code, it's more or less just copy/pasted from the Consumer code to the Runloop.
The only change is that I need a `Promise` now to return the `InvalidSubscriptionUnion` to fail when the user creates a new consuming session with an invalid `Subscription`.
See https://github.com/zio/zio-kafka/pull/857#discussion_r1233063581

2023-06-18 09:22 UTC, guizmaii commented on zio-kafka-bench/src/main/scala/zio/kafka/bench/comparison/ComparisonBenchmark.scala
> +        // Absurdly high timeout to avoid the runloop from being interrupted while we're benchmarking other stuff
> I'd expect it to not cause any errors anymore because the timeout only starts when we start consuming, right?

Yes, it does start only when we consume. 
Let me check 🤔

2023-06-24 09:01 UTC, guizmaii commented
@erikvanoosten FYI, I remove the retry mechanism in the `RunloopAccess::stopConsumption` method. See https://github.com/zio/zio-kafka/pull/857/commits/75589412ff39a43bd187877a3966efdbf9e61110

2023-06-24 09:03 UTC, guizmaii commented on zio-kafka-bench/src/main/scala/zio/kafka/bench/comparison/ComparisonBenchmark.scala
> +        // Absurdly high timeout to avoid the runloop from being interrupted while we're benchmarking other stuff
I'd prefer to leave it like this for now. Hopefully, we'll manage to remove this global `runloopTimeout` settings

2023-06-24 13:26 UTC, erikvanoosten approved these changes

2023-06-24 16:44 UTC, guizmaii commented
FYI, I renamed `RunloopState.Stopped` to `RunloopState.Finalized` to make it clearer that a Runloop can't be restarted

2023-06-25 08:50 UTC, svroonland commented on zio-kafka-test/src/test/scala/zio/kafka/consumer/SubscriptionsSpec.scala
> +        consumer_0 =
Can we stick to camel casing?

2023-07-01 07:42 UTC, svroonland approved these changes

2023-07-01 13:23 UTC, merged